---
aws_credentials_script: "{{ lookup('template', 'aws_credentials.j2.groovy') }}"
ssh_credentials_script: "{{ lookup('template', 'ssh_credentials.j2.groovy') }}"
k8s_key_file: "~/.ansible/tmp/k8s.key"